// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServer.Models;

public partial class ClassSchedule
{
    public int SchedulerId { get; set; }

    public int CourseId { get; set; }

    public DateTime Scheduler { get; set; }
}