// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServer.Models;

public partial class Course
{
    public int CourseId { get; set; }

    public string CourseName { get; set; }

    public int TrainerId { get; set; }

    public string PetCategory { get; set; }

    public string CourseCategory { get; set; }

    public string CourseType { get; set; }

    public string Description { get; set; }

    public string ApprovalStatus { get; set; }

    public decimal Price { get; set; }

    public string Location { get; set; }

    public int? MaxParticipants { get; set; }

    public int? EnrollmentCount { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public int? Clicks { get; set; }

    public string ThumbnailUrl { get; set; }
}