// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServer.Models;

public partial class CourseRating
{
    public int CourseRatingId { get; set; }

    public int CourseId { get; set; }

    public int TrainerId { get; set; }

    public int UserId { get; set; }

    public int Rating { get; set; }

    public string Comment { get; set; }

    public DateTime RatingDate { get; set; }
}