// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServer.Models;

public partial class Pet
{
    public int PetId { get; set; }

    public string PetName { get; set; }

    public string PetType { get; set; }

    public string Gender { get; set; }

    public double Weight { get; set; }

    public string Breed { get; set; }

    public int MemberId { get; set; }

    public DateTime Birthday { get; set; }
}