// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServer.Models;

public partial class TrainerServiceArea
{
    public int TeachingAreaId { get; set; }

    public int LocationId { get; set; }

    public int TrainerId { get; set; }
}