// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServer.Models;

public partial class Trainer
{
    public int TrainerId { get; set; }

    public int MemberId { get; set; }

    public string TrainerName { get; set; }

    public string Specialization { get; set; }

    public string Experience { get; set; }

    public string Qualifications { get; set; }

    public string Status { get; set; }

    public string Photo { get; set; }
}